[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "=2.0.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
store = { path = "../store" }
