[package]
name = "stream"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
redis = { version = "0.23", features = ["tokio-comp", "streams"] }
anyhow = "1.0.75"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.3.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tonic-reflection = "0.6"
tonic-web = "0.4"
tower-http = { version = "0.3", features = ["cors"] }

[build-dependencies]
tonic-build = "0.8"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"
