[package]
name = "laser-ingest"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bs58 = "0.5.1"
dotenvy = "0.15"
futures-util = { version = "0.3", features = ["sink"] }
helius-laserstream = { path = "../../helius-laserstream" }
prost = "0.13"
redis = { version = "0.27", features = ["tokio-comp", "aio"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }
tokio-tungstenite = { version = "0.23.0", features = ["native-tls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tungstenite = "0.23.0"
