[package]
name = "laser-ingest"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
helius-laserstream = "0.0.7"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15.7"
tracing-subscriber = "0.3.18"
anyhow = "1.0.86"
futures-util = "0.3.30"
bs58 = "0.5.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.21"
borsh = "1.5.1"
async-trait = "0.1.88"
serde_json = "1.0.141"
redis = { version = "0.24", features = ["aio", "tokio-comp"] }
tracing = "0.1"

[dev-dependencies]
